language: go
go:
  - 1.9.x
  - 1.10.x
sudo: false

cache:
  directories:
    - ~/.cache

install:
    - go get -v github.com/golang/dep/cmd/dep
    - dep ensure
    - go install ./...
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
script:
  - ./goclean.sh
