language: go
go:
  - 1.8.x
  - 1.9.x
sudo: false
before_install:
  - gotools=golang.org/x/tools
install:
  - go get -v github.com/Masterminds/glide
  - glide install
  - go get -v $gotools/cmd/cover
  - go get -v github.com/bradfitz/goimports
  - go get -v github.com/golang/lint/golint
script:
  - export PATH=$PATH:$GOPATH/bin
  - go install $(glide nv)
