language: go
go:
  - 1.9.x
  - 1.10.x
sudo: false
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$GOPATH/bin
  - ./run_tests.sh
