name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
        go: [1.14, 1.15]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Go Build
      env:
        GO111MODULE: "on"
      run: go build ./...

    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build

    - name: Install Linters
      run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.0"
    - name: tests
      env:
        GO111MODULE: "on"
      run: |
        ./run_tests.sh
